### ISSUE TITLE
Can we have React and angular together in single-spa?

### ISSUE THREAD

**Issue by ajaykumarsana** [react-microfrontends/people#14]
Hi @joeldenning ,
I've been going through single-spa tutorials and examples, I found examples for "**angular micro front end**" and "**react micro front end**" individually. I couldn't find combination of both, So can we have both together?

Thanks,
Ajay

**Comment by internettrans** [comment]
Yes, you can. See https://github.com/polyglot-microfrontends and https://github.com/joeldenning/simple-single-spa-webpack-example. I would not recommend using the simple-single-spa-webpack-example code yourself - it's quite old and uses an old version of Angular. For Angular, you really have to use Angular CLI in order for things to work nowadays, and that example doesn't.
