### ISSUE TITLE
It always show Your Microfrontend is not here page

### ISSUE THREAD

**Issue by oliverchengui** [react-microfrontends/people#37]
I have already follow the guide and override the path in https://react.microfrontends.app/ and refresh the page. it always redirect to our Microfrontend is not here page. Is there anyone know how to fix it?

**Comment by oliverchengui** [comment]
Looks like `root-config` need to upgrade single-spa version to `6.0.2`. Currently, it is ` ^5.9.3`

**Comment by internettrans** [comment]
Fix released in webpack-config-single-spa@7 and upgraded in https://github.com/react-microfrontends/people/pull/44
